module.exports = {
    'parser': 'babel-eslint',
    'env': {
        'es6': true
    },
    'ecmaFeatures': {
        'arrowFunctions': true,
        'binaryLiterals': false,
        'blockBindings': true,
        'classes': true,
        'defaultParams': true,
        'destructuring': true,
        'forOf': true,
        'generators': false,
        'globalReturn': false,
        'jsx': true,
        'modules': true,
        'objectLiteralComputedProperties': true,
        'objectLiteralDuplicateProperties': false,
        'objectLiteralShorthandMethods': true,
        'objectLiteralShorthandProperties': true,
        'octalLiterals': false,
        'regexUFlag': false,
        'regexYFlag': false,
        'restParams': false,
        'spread': true,
        'superInFunctions': true,
        'templateStrings': true,
        'unicodeCodePointEscapes': false
    },
    'rules': {
        'arrow-body-style': 2,
        'arrow-parens': 2,
        'arrow-spacing': 2,
        'constructor-super': 2,
        'generator-star-spacing': 2,
        'no-arrow-condition': 2,
        'no-class-assign': 2,
        'no-const-assign': 2,
        'no-dupe-class-members': 2,
        'no-this-before-super': 2,
        'no-var': 2,
        'object-shorthand': 2,
        'prefer-arrow-callback': 0,
        'prefer-const': 2,
        'prefer-reflect': 2,
        'prefer-spread': 2,
        'prefer-template': 2,
        'require-yield': 2
    }
};