module.exports = {
    'globals': {
        '$': true,
        '$$': true,
        '_': true,
        'beforeAll': true,
        'afterAll': true,
        'beforeEachProviders': false,
        'inject': false,
        'browser': true,
        'beforeEach': true,
        'afterEach': true,
        'injectAsync': true,
        'async': true,
        'by': true,
        'describe': true,
        'Dropzone': true,
        'element': true,
        'expect': true,
        'hljs': true,
        'io': true,
        'it': true,
        'jasmine': true,
        'Mockery': true,
        'Promise': true,
        'spyOn': true,
        'state': true,
        'System': true,
        'xdescribe': true,
        'xit': true
    }
}