module.exports = {
    'rules': {
        'array-bracket-spacing': [2, 'never'],
        'camelcase': [2, {'properties': 'always'}],
        'comma-spacing': [2, {'before': false, 'after': true}],
        'comma-style': [2, 'last'],
        'computed-property-spacing': [2, 'never'],
        'consistent-this': 0, // Too many use-cases for reassigning 'this' to different values
        'eol-last': 2,
        'func-names': 2,
        'func-style': [2, 'declaration'],
        'key-spacing': [2, {'beforeColon': false, 'afterColon': true}],
        'lines-around-comment': 0,
        'linebreak-style': [2, 'unix'],
        'new-parens': 2,
        'newline-after-var': 0,
        'no-array-constructor': 2,
        'no-continue': 2,
        'no-inline-comments': 0,
        'no-lonely-if': 2,
        'no-multiple-empty-lines': 0,
        'no-nested-ternary': 2,
        'no-new-object': 2,
        'no-spaced-func': 2,
        'no-ternary': 0,
        'no-trailing-spaces': [2, {'skipBlankLines': true}],
        'no-underscore-dangle': 0,
        'no-unneeded-ternary': 2,
        'object-curly-spacing': [2, 'never'],
        'one-var': [2, {'uninitialized': 'always', 'initialized': 'never'}],
        'operator-assignment': 0, // readability on a case-by-case basis
        'operator-linebreak': [2, 'after'],
        'padded-blocks': 0,
        'quote-props': [2, 'as-needed'],
        'semi-spacing': [2, {'before': false, 'after': true}],
        'semi': [2, 'never'],
        'sort-vars': 0,
        'space-after-keywords': [2, 'always'],
        'space-before-blocks': [2, 'always'],
        'space-before-function-paren': [2, 'never'],
        'space-in-parens': [2, 'never'],
        'space-return-throw-case': 2,
        'space-unary-ops': [2, {'words': true, 'nonwords': false}],
        'spaced-comment': 0,
        'wrap-regex': 0,
        'constructor-super': 2,
        'generator-star-spacing': [2, {'before': false, 'after': true}],
        'no-this-before-super': 2,
        'object-shorthand': [2, 'properties'], // methods are optional so you can specify a name if you want
        'max-params': [2, 5],
        'no-bitwise': 2,
        'no-plusplus': 0
    }
};