module.exports = {
    'rules': {
        'array-bracket-spacing': 2,
        'block-spacing': 2,
        'brace-style': [2, '1tbs', {'allowSingleLine': true}],
        'camelcase': [2, {'properties': 'never'}],
        'comma-spacing': 2,
        'comma-style': 2,
        'computed-property-spacing': 2,
        'consistent-this': 0,
        'eol-last': 2,
        'func-names': 2,
        'func-style': [2, 'declaration'],
        'id-length': 0,
        'id-match': 0,
        'indent': [2, 4],
        'jsx-quotes': [2, 'prefer-double'],
        'key-spacing': 2,
        'linebreak-style': 0,
        'lines-around-comment': 0,
        'max-nested-callbacks': 0,
        'new-cap': [2, {'newIsCap': true}],
        'new-parens': 2,
        'newline-after-var': 0,
        'no-array-constructor': 2,
        'no-continue': 0,
        'no-inline-comments': 0,
        'no-lonely-if': 2,
        'no-mixed-spaces-and-tabs': 2,
        'no-multiple-empty-lines': [2, {'max': 1}],
        'no-negated-condition': 2,
        'no-nested-ternary': 2,
        'no-new-object': 2,
        'no-restricted-syntax': 0,
        'no-spaced-func': 2,
        'no-ternary': 0,
        'no-trailing-spaces': 2,
        'no-underscore-dangle': 0,
        'no-unneeded-ternary': 2,
        'object-curly-spacing': 2,
        'one-var': [2, 'never'],
        'operator-assignment': [2, 'always'],
        'operator-linebreak': 0,
        'padded-blocks': [2, 'never'],
        'quote-props': [2, 'as-needed'],
        'quotes': [2, 'single', 'avoid-escape'],
        'require-jsdoc': 0,
        'semi-spacing': 2,
        'semi': 2,
        'sort-vars': 2,
        'space-after-keywords': 2,
        'space-before-blocks': 2,
        'space-before-keywords': 2,
        'space-before-function-paren': 2,
        'space-in-parens': 2,
        'space-infix-ops': 2,
        'space-return-throw-case': 2,
        'space-unary-ops': 2,
        'spaced-comment': [2, 'always', {
            'exceptions': ['-', '+'],
            'markers': ['=', '!']
        }],
        'wrap-regex': 2
    }
};